"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  const pathName = usePathname();
  const currentPath = pathName;

  return (
    <html lang="en" className="bg-primary text-white">
      <body className={inter.className}>
        <div className="flex">
          {currentPath !== "/signin" && <Sidebar />}
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
